### ISSUE TITLE
Add types-aiobotocore build

### ISSUE THREAD

**Issue by vemel** [conda-forge/boto3-stubs-feedstock#188]
Starting from `7.0.0` release `mypy-boto3-builder` also builds type annotations for [aiobotocore](https://github.com/aio-libs/aiobotocore)

Produced packages:
- `types-aiobotocore` - similar to `boto3-stubs`
- `types-aiobotocore-lite` - similar to `boto3-stubs-lite`
- `types-aiobotocore-ec2`
- `types-aiobotocore-rds`
- `types-aiobotocore-s3`
- `types-aiobotocore-lambda`
- `types-aiobotocore-sqs`
- `types-aiobotocore-cloudformation`
- `types-aiobotocore-dynamodb`

Please let me know if you are interested and have time for this.

**Comment by maresb** [comment]
Seems like a lot of work and I'm tight on time these days. Maybe I could help you through the process of submitting to conda-forge/staged-recipes? If you know a few tricks it's not much work.

**Comment by maresb** [comment]
I'd do something like the following:
```
mamba create --name forge --channel=conda-forge mamba boa grayskull
conda activate forge
git clone https://github.com/conda-forge/staged-recipes.git
cd staged-recipes/recipes
git checkout -b types-aiobotocore
grayskull pypi types-aiobotocore
cd recipes
conda mambabuild .
# Fix any errors about building locally, and compare any differences with `boto3-stubs`
git commit -m "Add types-aiobotocore"
# Create PR and follow instructions there
```

I haven't tested this so there might be typos and steps missing, but that should get you most of the way with minimal effort.

Ah, and you'll want to make sure that there's `noarch: python` because sometimes Grayskull finds a selector (e.g. `#  [linux]`) which can be removed.

Let me know if you have any questions. Good luck!
